# Generated by Django 5.1.4 on 2026-02-21 11:30

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars', validators=[users.models.validate_image_extension], verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(null=True, upload_to='banners', validators=[users.models.validate_image_extension], verbose_name='Баннер'),
        ),
    ]
