# Generated by Django 5.1.4 on 2025-12-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='out_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Новая цена'),
        ),
    ]
