# Generated by Django 6.0.6 on 2026-06-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными курьеру'), ('card', 'Банковской картой курьеру')], max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
